//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SunglassStoreServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin_Login
    {
        public int LoginID { get; set; }
        public int EmpID { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public int RoleType { get; set; }
        public string Notes { get; set; }
    
        public virtual Admin_Employee Admin_Employee { get; set; }
        public virtual Role Role { get; set; }
    }
}
